# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  
  # Máquina servidor web
  config.vm.define "web" do |web|
    web.vm.hostname = "servidor-web"
	web.memory = "4096"
	web.cpus = "2"
    web.vm.network "forwarded_port", guest: 80, host: 8090
    web.vm.network "private_network", ip: "192.168.56.3"
    web.vm.provision "shell", inline: <<-WEB
      apt update
      apt install apache2 -y
      systemctl restart apache2
    WEB
  end
  
  # Máquina banco de dados
  config.vm.define "database" do |database|
    database.vm.hostname = "servidor-database"
    database.vm.network "forwarded_port", guest: 80, host: 8091
    database.vm.network "private_network", ip: "192.168.56.4"
    database.vm.provision "shell", inline: <<-DATABASE
      apt update
      apt install mariadb-server -y
	  sed -i "s/^bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
      systemctl restart mariadb.service
    DATABASE
  end
end
